### ISSUE TITLE
Can MatchZoo beat Elasticsearch for Product Search

### ISSUE THREAD

**Issue by gtsoukas** [NTMC-Community/MatchZoo#486]
I want to proof that goodness of product search (e.g. in terms of NDCG@10 metric) in a retail company can be significantly improved by the use of neural models such as the duet architecture. Currently  Elasticsearch/Solr is used for product search. From a theoretical perspective neural model should be superior since they are a) better able to capture multidimensional meaning via distributed representations and b) they are able to capture interaction information such as in collaborative filtering. Is this something I can do with MatchZoo? At the moment it is not about a production ready system.

If true, how would the training data look like? I was thinking to generate _positive_ and _negative_ training examples. For one positive training example I would generate e.g. ten negative examples.

A positive example would look like the following:
`1    <query>     <product name and description>`
or
`1    headphones    sennheiser hd1 wireless headphones with active noise cancellation - Black Closed back, around-ear design ...`

A negative example would look like the following:
`0   <query>    <product name and description>`
`0    headphones    radio flyer deluxe big flyer, red chopper-style tricycle with sleek racing design...`

Negative examples would be generated by random sampling. Positive examples are harder to generate, One approach would be to mix different sources to generate related queries, e.g. product category names, noisy click data from web-search, synonyms, transaction data for weighting etc.

Any feedback is highly appreciated.

**Comment by faneshion** [comment]
To run MatchZoo, you can prepare the datasets as [this sample file](https://github.com/NTMC-Community/MatchZoo/blob/2.0-dev/matchzoo/datasets/toy/train_rank.txt). Then, you can follow this [tutorial](https://github.com/NTMC-Community/MatchZoo/blob/2.0-dev/notebooks/tutorial.ipynb) to run the code. Since we are working on the 2.0 version of matchzoo, there may be some bugs. Hope you can give us more suggestions.

**Comment by gtsoukas** [comment]
What version of MatchZoo and what version of python should i use to reproduce the above tutorial? I am having trouble with very basic stuff e.g. ```from matchzoo import preprocessor``` -> ```ImportError: cannot import name preprocessor```.

**Comment by faneshion** [comment]
Recently, we have refactored some code. The [sandbox](https://github.com/NTMC-Community/MatchZoo/blob/2.0-dev/sandbox.ipynb) is more stable than the tutorial.

**Comment by bwanglzu** [comment]
currently matchzoo 2.0 only support python 3.6, 3.x will be supported in the future. We'll not support python 2.x.
